#! /bin/zsh

# for hiding information, change $hide to 1
hide=0
user_name=`git config --global --get user.name`;
total_project_dir=`ls | wc -w`
total_project_dir_cnt=0;
total_add=0; 
total_sub=0;
total=0; 

if [[ -z $hide ]]; then
	print "Counting user \""$user_name"\" contribution lines"
	print "workspace : \"$PWD\"";
else
	print "Counting user \""${user_name//[a-zA-Z0-9]/*}"\" contribution lines"
	print "workspace : \"${PWD//[a-zA-Z0-9]/*}\"";
fi

print "\nproject\033[100D\033[16C| + add\033[100D\033[32C- sub\033[100D\033[48C= total";
print "\033[2K\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-";
for project_dir in `ls -w 1`; do
	if [[ -z $hide ]]; then
		project_name=$project_dir;
	else
		project_name=${project_dir//[a-zA-Z0-9]/*};
	fi
	print "\033[2K"$total_project_dir_cnt" / "$total_project_dir"\t"$project_name;
	printf "\033[1A";
	if [[ $project_dir =~ "linux*" ]]; then 
		print "\033[2Kskip "$project_name"\033[1A"; 
		continue; 
	fi;
	git_log=`git --git-dir=$project_dir/.git log --author="$user_name" --pretty=tformat: --numstat 2>&1`;
	if [[ $git_log =~ "fatal\: Not a git repository*" ]]; then
		continue; 
	fi;
	now_add=`echo $git_log | awk '{ 
		now_add += $1; 
	} END { 
		printf now_add;
	}'`
	now_sub=`echo $git_log | awk '{ 
		now_sub += $2; 
	} END { 
		printf now_sub;
	}'`
	if [[ $now_add>0 ]] || [[ $now_sub>0 ]]; then
		now_total=$(( now_add - now_sub ));
		total=$(( total + now_total ));
		total_add=$(( total_add + now_add ));
		total_sub=$(( total_sub + now_sub ));
		print "\033[2K"$project_name"\033[100D\033[16C| + "$now_add"\033[100D\033[32C- "$now_sub"\033[100D\033[48C= "$now_total;
	fi;
	total_project_dir_cnt=$(( total_project_dir_cnt + 1));
done;
print "\033[2K\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-";
print "TOTAL\033[100D\033[16C| + "$total_add"\033[100D\033[32C- "$total_sub"\033[100D\033[48C= "$total;